Repository DGtal-team/DGtal, pull requests merged in 2018-11, with the labels that each got.

#1356 Fix bug in ImageLinearCellEmbedder
  ChangeLog.md
  examples/shapes/viewMarchingCubes.cpp
  src/DGtal/images/ImageLinearCellEmbedder.ih
Labels: BugFix, Image, ready for review :+1:

#1358 Multi stat one sample
  ChangeLog.md
  src/DGtal/math/MultiStatistics.ih
  src/DGtal/topology/doc/moduleCubicalComplex.dox
Labels: Arithmetic, BugFix, Build

#1366 Fixing warning of Clang when including GraphicsMagick 1.3.31
  ChangeLog.md
  src/DGtal/io/readers/MagickReader.h
  src/DGtal/io/writers/MagickWriter.h
Labels: Build, ready for review :+1:

#1364 Some fixes for DGtal for dummies
  ChangeLog.md
  examples/tutorial-examples/shortcuts-geometry.cpp
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/helpers/ShortcutsGeometry.h
  src/DGtal/io/colormaps/TickedColorMap.h
  src/DGtal/io/colormaps/TickedColorMap.ih
  src/DGtal/shapes/MeshHelpers.h
  src/DGtal/shapes/MeshHelpers.ih
  src/DGtal/shapes/PolygonalSurface.h
  src/DGtal/shapes/PolygonalSurface.ih
  src/DGtal/shapes/TriangulatedSurface.h
  src/DGtal/shapes/TriangulatedSurface.ih
  src/DGtal/shapes/doc/moduleHalfEdgeMesh.dox
  tests/shapes/testPolygonalSurface.cpp
  tests/shapes/testTriangulatedSurface.cpp
Labels: BugFix, Documentation, FeatureRequest

#1365 square norm in pointvector
  ChangeLog.md
  src/DGtal/kernel/PointVector.h
  src/DGtal/kernel/PointVector.ih
  tests/kernel/testPointVector-catch.cpp
Labels: ready for review :+1:
