Repository DGtal-team/DGtal, pull requests merged in 2019-08, with the labels that each got.

#1425 Typos/minor edits in ChamferNorm
  src/DGtal/geometry/volumes/distance/ChamferNorm2D.h
Labels: ready for review :+1:

#1434 Fixing doxygen source url by downloading it from SourceForge
  .travis/install_doxygen.sh
  ChangeLog.md
Labels: Documentation

#1432 Adding a new image in the Distance Transformation doc
  ChangeLog.md
  src/DGtal/geometry/doc/images/DTmetrics-small.png
  src/DGtal/geometry/doc/images/DTmetrics.png
  src/DGtal/geometry/doc/moduleVolumetric.dox
Labels: Documentation, ready for review :+1:

#1431 Build corrections
  ChangeLog.md
  src/Board/Point.h
  src/DGtal/base/Alias.h
  src/DGtal/base/ConstAlias.h
  src/DGtal/geometry/curves/FrechetShortcut.h
  src/DGtal/geometry/curves/FrechetShortcut.ih
  src/DGtal/geometry/curves/OneBalancedWordComputer.h
  src/DGtal/geometry/tools/MelkmanConvexHull.h
  src/DGtal/helpers/Parameters.h
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/images/ConstImageAdapter.h
  src/DGtal/images/ImageAdapter.h
  src/DGtal/io/readers/DicomReader.ih
  src/DGtal/math/linalg/SimpleMatrix.h
  src/DGtal/shapes/fromPoints/Point2ShapePredicate.h
  src/DGtal/shapes/parametric/Lemniscate2D.ih
  tests/shapes/testAstroid2D.cpp
  tests/topology/testHalfEdgeDataStructure.cpp
Labels: ready for review :+1:

#1414 Add a moveTo() function in implicit and star shapes
  ChangeLog.md
  src/DGtal/shapes/implicit/ImplicitBall.h
  src/DGtal/shapes/implicit/ImplicitHyperCube.h
  src/DGtal/shapes/implicit/ImplicitNorm1Ball.h
  src/DGtal/shapes/implicit/ImplicitRoundedHyperCube.h
  src/DGtal/shapes/parametric/AccFlower2D.h
  src/DGtal/shapes/parametric/Astroid2D.h
  src/DGtal/shapes/parametric/Ball2D.h
  src/DGtal/shapes/parametric/Ball3D.h
  src/DGtal/shapes/parametric/Ellipse2D.h
  src/DGtal/shapes/parametric/Flower2D.h
  src/DGtal/shapes/parametric/Lemniscate2D.h
  src/DGtal/shapes/parametric/NGon2D.h
  src/DGtal/shapes/parametric/StarShaped2D.h
  src/DGtal/shapes/parametric/StarShaped3D.h
  tests/shapes/CMakeLists.txt
  tests/shapes/testShapeMoveCenter.cpp
Labels: ready for review :+1:
