Repository DGtal-team/DGtal, pull requests merged in 2019-06, with the labels that each got.

#1412 Normal obj
  ChangeLog.md
  examples/tutorial-examples/shortcuts-geometry.cpp
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/geometry/surfaces/estimation/LocalEstimatorFromSurfelFunctorAdapter.h
  src/DGtal/geometry/surfaces/estimation/LocalEstimatorFromSurfelFunctorAdapter.ih
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/helpers/ShortcutsGeometry.h
  src/DGtal/math/linalg/SimpleMatrix.ih
Labels: BugFix, IO-Visualisation, ready for review :+1:

#1415 Update documented boost minimal version to match cmake script.
  README.md
  src/DGtal/doc/moduleBuildDGtal.dox
Labels: Documentation, ready for review :+1:

#1413 Removing std namespace in header
  ChangeLog.md
  examples/geometry/surfaces/exampleIntegralInvariantCurvature3D.cpp
  src/DGtal/io/viewers/Viewer3D.ih
Labels: BugFix, IO-Visualisation, ready for review :+1:

#1418 Upgrading to Catch2
  ChangeLog.md
  examples/doc-examples/DGtalCatch.h
  examples/doc-examples/catch.hpp
  examples/doc-examples/exampleCatch.cpp
  src/DGtal/geometry/surfaces/estimation/LocalEstimatorFromSurfelFunctorAdapter.ih
  tests/base/testSetFunctions.cpp
  tests/catch.hpp
  tests/kernel/testPointVector.cpp
  tests/math/testRealFFT.cpp
  tests/topology/testNeighborhoodConfigurations.cpp
  tests/topology/testVoxelComplex.cpp
Labels: Build, ready for review :+1:

#1417 Shortcut doc
  ChangeLog.md
  src/DGtal/doc/mainpage.dox
Labels: Documentation, ready for review :+1:

#1419 Upgrading to Catch 2.9
  ChangeLog.md
  examples/doc-examples/catch.hpp
  tests/DGtalCatch.h
  tests/catch.hpp
  tests/kernel/testPointVector.cpp
Labels: Build, ready for review :+1:
