Repository DGtal-team/DGtal, pull requests merged in 2019-02, with the labels that each got.

#1388 LpMetric in R^d
  ChangeLog.md
  examples/geometry/surfaces/exampleEstimatorFromSurfelFunctors.cpp
  src/DGtal/geometry/doc/moduleMetrics.dox
  src/DGtal/geometry/surfaces/estimation/LocalEstimatorFromSurfelFunctorAdapter.h
  src/DGtal/geometry/surfaces/estimation/VoronoiCovarianceMeasureOnDigitalSurface.h
  src/DGtal/geometry/surfaces/estimation/VoronoiCovarianceMeasureOnDigitalSurface.ih
  src/DGtal/geometry/volumes/distance/CMetricSpace.h
  src/DGtal/geometry/volumes/distance/LpMetric.h
  tests/geometry/surfaces/testLocalEstimatorFromFunctorAdapter.cpp
  tests/geometry/surfaces/testSphericalHoughNormalVectorEstimator.cpp
  tests/geometry/surfaces/testTensorVoting.cpp
  tests/geometry/volumes/distance/CMakeLists.txt
  tests/geometry/volumes/distance/testLpMetric.cpp
Labels: Geometry, ready for review :+1:

#1382 Update CowPtr and Clone to fix testClone2
  ChangeLog.md
  src/DGtal/base/Clone.h
  src/DGtal/base/CowPtr.h
  tests/base/testClone2.cpp
Labels: Base, BugFix, ready for review :+1:

#1390 Fix cubical complex functions
  ChangeLog.md
  examples/topology/cubical-complex-collapse.cpp
  examples/topology/cubical-complex-illustrations.cpp
  src/DGtal/io/viewers/Viewer3D.ih
  src/DGtal/topology/CubicalComplex.h
  src/DGtal/topology/CubicalComplex.ih
  src/DGtal/topology/CubicalComplexFunctions.h
  src/DGtal/topology/CubicalComplexFunctions.ih
  src/DGtal/topology/doc/moduleCubicalComplex.dox
  tests/topology/testCubicalComplex.cpp
Labels: BugFix, Topology, ready for review :+1:

#1384 Warnings corrections
  ChangeLog.md
  examples/geometry/curves/estimation/exampleCurvature.cpp
  examples/topology/ctopo-2.cpp
  examples/tutorial-examples/FMMErosion.cpp
  examples/tutorial-examples/freemanChainFromImage.cpp
  src/DGtal/geometry/surfaces/estimation/IntegralInvariantCovarianceEstimator.ih
  src/DGtal/geometry/surfaces/estimation/IntegralInvariantVolumeEstimator.ih
  src/DGtal/geometry/volumes/distance/FMM.ih
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/helpers/ShortcutsGeometry.h
  src/DGtal/io/Display2DFactory.ih
  src/DGtal/io/Display3DFactory.ih
  src/DGtal/shapes/Shapes.ih
  src/DGtal/shapes/parametric/StarShaped3D.ih
  src/DGtal/topology/DigitalSurface.ih
  tests/geometry/curves/estimation/testEstimatorComparator.cpp
  tests/geometry/curves/estimation/testLengthEstimators.cpp
  tests/geometry/curves/estimation/testTrueLocalEstimator.cpp
  tests/geometry/curves/testStabbingCircleComputer.cpp
  tests/geometry/volumes/distance/testFMM.cpp
  tests/topology/testDigitalSurface.cpp
  tests/topology/testVoxelComplex.cpp
Labels: Build

#1386 fix VS contour helper
  ChangeLog.md
  src/DGtal/geometry/helpers/ContourHelper.ih
Labels: BugFix, waiting author feedbacks

#1389 Warnings xcode
  ChangeLog.md
  examples/geometry/tools/determinant/exampleInHalfPlane.cpp
  examples/tutorial-examples/shortcuts-geometry.cpp
  examples/tutorial-examples/shortcuts.cpp
  src/Board/Shapes.cpp
  src/DGtal/base/LabelledMap.h
  src/DGtal/base/LabelledMap.ih
  src/DGtal/base/OrderedAlphabet.ih
  src/DGtal/geometry/curves/FreemanChain.ih
  src/DGtal/geometry/curves/estimation/LambdaMST2D.ih
  src/DGtal/geometry/helpers/ContourHelper.ih
  src/DGtal/geometry/surfaces/DigitalSurfaceConvolver.ih
  src/DGtal/geometry/surfaces/estimation/estimationFunctors/SphericalHoughNormalVectorEstimator.h
  src/DGtal/geometry/tools/MelkmanConvexHull.ih
  src/DGtal/geometry/tools/SphericalAccumulator.h
  src/DGtal/io/Display2DFactory.ih
  src/DGtal/io/colormaps/HueShadeColorMap.ih
  src/DGtal/kernel/sets/DigitalSetDomain.ih
  src/DGtal/topology/CubicalComplex.ih
  src/DGtal/topology/DigitalSurface2DSlice.ih
  src/DGtal/topology/HalfEdgeDataStructure.h
  src/DGtal/topology/VoxelComplex.ih
  tests/arithmetic/testLatticePolytope2D.cpp
  tests/arithmetic/testLightSternBrocot.cpp
  tests/arithmetic/testLighterSternBrocot.cpp
  tests/arithmetic/testModuloComputer.cpp
  tests/arithmetic/testSternBrocot.cpp
  tests/base/testBits.cpp
  tests/base/testCountedConstPtrOrConstPtr.cpp
  tests/base/testLabelledMap-benchmark.cpp
  tests/base/testLabelledMap.cpp
  tests/base/testMultiMap-benchmark.cpp
  tests/geometry/curves/testDSLSubsegment.cpp
  tests/geometry/surfaces/testCOBAGenericNaivePlaneComputer-benchmark.cpp
  tests/geometry/surfaces/testCOBAGenericStandardPlaneComputer.cpp
  tests/geometry/surfaces/testCOBANaivePlaneComputer-benchmark.cpp
  tests/geometry/surfaces/testCOBANaivePlaneComputer.cpp
  tests/geometry/surfaces/testChordGenericStandardPlaneComputer.cpp
  tests/geometry/surfaces/testChordNaivePlaneComputer-benchmark.cpp
  tests/geometry/surfaces/testChordNaivePlaneComputer.cpp
  tests/geometry/volumes/distance/testPowerMap.cpp
  tests/geometry/volumes/distance/testReducedMedialAxis.cpp
  tests/geometry/volumes/testKanungo.cpp
  tests/graph/testDigitalSurfaceBoostGraphInterface.cpp
  tests/images/testImageSimple.cpp
  tests/shapes/testPolygonalSurface.cpp
  tests/shapes/testTriangulatedSurface.cpp
  tests/topology/testHalfEdgeDataStructure.cpp
  tests/topology/testImplicitDigitalSurface-benchmark.cpp
  tests/topology/testLightImplicitDigitalSurface-benchmark.cpp
  tests/topology/testObject.cpp
  tests/topology/testUmbrellaComputer.cpp
  tests/topology/testVoxelComplex.cpp
Labels: Build, ready for review :+1:

#1395 Correcting Cmake files for Windows and Visual Studio, and adding d suffix for the generated library in debug mode
  AUTHORS
  ChangeLog.md
  cmake/Common.cmake
  cmake/DGtalConfig.cmake.in
  cmake/FindFFTW3.cmake
  cmake/TargetDoxygenDox.cmake
  examples/tutorial-examples/CMakeLists.txt
Labels: Build
