Repository DGtal-team/DGtal, pull requests merged in 2020-04, with the labels that each got.

#1475 Fix const iterator issue1437
  ChangeLog.md
  examples/geometry/volumes/distance/toricdomainvolumetric.cpp
  examples/kernel/examplePointFunctorHolder.cpp
  examples/tutorial-examples/shapeDTViewer.cpp
  examples/tutorial-examples/volDTGranulo-template.cpp
  examples/tutorial-examples/volDTGranulo.cpp
  src/DGtal/base/ConstIteratorAdapter.h
Labels: ready for review :+1:

#1470 Implicit polynomial 3D shape principal curvatures and principal directions
  ChangeLog.md
  examples/tutorial-examples/shortcuts-geometry.cpp
  src/DGtal/doc/global.bib
  src/DGtal/doc/tutorials/images/goursat-primal-d1-d2.png
  src/DGtal/doc/tutorials/images/torus-primal-d1-d2.png
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/helpers/ShortcutsGeometry.h
  src/DGtal/shapes/ShapeGeometricFunctors.h
  src/DGtal/shapes/implicit/ImplicitPolynomial3Shape.h
  src/DGtal/shapes/implicit/ImplicitPolynomial3Shape.ih
Labels: Geometry, ready for review :+1:

#1479 add cmake cxx std in minimal example
  src/DGtal/doc/moduleHowToUseDGtal.dox
Labels: ready for review :+1:

#1476 Add export off in DGtal::Shortcut
  ChangeLog.md
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/io/Color.h
  src/DGtal/io/Color.ih
Labels: ready for review :+1:

#1481 Fix1478
  ChangeLog.md
  src/DGtal/topology/CubicalComplex.h
Labels: Build, Compilation Issue, Topology, waiting author feedbacks
