Repository DGtal-team/DGtal, pull requests merged in 2020-03, with the labels that each got.

#1460 New Integral Invariant functor
  ChangeLog.md
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/geometry/surfaces/estimation/IIGeometricFunctors.h
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/helpers/ShortcutsGeometry.h
  tests/geometry/surfaces/CMakeLists.txt
  tests/geometry/surfaces/testIntegralInvariantCovarianceEstimator.cpp
  tests/geometry/surfaces/testIntegralInvariantShortcuts.cpp
Labels: Geometry, waiting author feedbacks

#1465 [WIP] Fixing Travis build
  .travis.yml
Labels: Build

#1464 Checking Travis build matrix
  AUTHORS
Labels: Build

#1462 Similar typedefs for parametric shape
  ChangeLog.md
  src/DGtal/geometry/curves/estimation/ParametricShapeArcLengthFunctor.h
  src/DGtal/shapes/parametric/AccFlower2D.h
  src/DGtal/shapes/parametric/AccFlower2D.ih
  src/DGtal/shapes/parametric/Astroid2D.h
  src/DGtal/shapes/parametric/Astroid2D.ih
  src/DGtal/shapes/parametric/Ball2D.h
  src/DGtal/shapes/parametric/Ball2D.ih
  src/DGtal/shapes/parametric/Ball3D.h
  src/DGtal/shapes/parametric/Ball3D.ih
  src/DGtal/shapes/parametric/Ellipse2D.h
  src/DGtal/shapes/parametric/Ellipse2D.ih
  src/DGtal/shapes/parametric/Flower2D.h
  src/DGtal/shapes/parametric/Flower2D.ih
  src/DGtal/shapes/parametric/Lemniscate2D.h
  src/DGtal/shapes/parametric/Lemniscate2D.ih
  src/DGtal/shapes/parametric/NGon2D.h
  src/DGtal/shapes/parametric/NGon2D.ih
  src/DGtal/shapes/parametric/StarShaped2D.h
  src/DGtal/shapes/parametric/StarShaped2D.ih
  src/DGtal/shapes/parametric/StarShaped3D.h
  src/DGtal/shapes/parametric/StarShaped3D.ih
  tests/shapes/testDigitalShapesDecorator.cpp
  tests/shapes/testGaussDigitizer.cpp
Labels: Shapes

#1471 Chanelog edit (preparing 1.1)
  ChangeLog.md
Labels: ProjectManagment, ready for review :+1:
