Repository DGtal-team/DGtal, pull requests merged in 2020-09, with the labels that each got.

#1508 Travis: Fix broken Eigen url. Update Eigen to 3.3.7.
  .travis/install_eigen.sh
  ChangeLog.md
Labels: Arithmetic, Kernel

#1506 CMake: Abort compilation if compiler is gcc 10.1 due to compiler bug.
  ChangeLog.md
  cmake/Common.cmake
Labels: Build

#1505 Fix loadTable in Windows
  ChangeLog.md
  src/DGtal/topology/NeighborhoodConfigurations.ih
Labels: Build

#1503 Surface mesh, a generic representation for polygonal surfaces
  ChangeLog.md
  examples/samples/spot.obj
  examples/shapes/CMakeLists.txt
  examples/shapes/exampleSurfaceMesh.cpp
  src/DGtal/doc/global.bib
  src/DGtal/io/readers/SurfaceMeshReader.h
  src/DGtal/io/readers/SurfaceMeshReader.ih
  src/DGtal/io/writers/SurfaceMeshWriter.h
  src/DGtal/io/writers/SurfaceMeshWriter.ih
  src/DGtal/shapes/MeshHelpers.h
  src/DGtal/shapes/MeshHelpers.ih
  src/DGtal/shapes/SurfaceMesh.h
  src/DGtal/shapes/SurfaceMesh.ih
  src/DGtal/shapes/SurfaceMeshHelper.h
  src/DGtal/shapes/SurfaceMeshHelper.ih
  src/DGtal/shapes/doc/images/exampleSurfaceMesh.jpg
  src/DGtal/shapes/doc/images/spot-bft-isolines.png
  src/DGtal/shapes/doc/moduleSurfaceMesh.dox
  src/DGtal/shapes/doc/packageShapes.dox
  src/DGtal/shapes/doc/packageShapesConcepts.dox
  src/DGtal/topology/HalfEdgeDataStructure.h
  tests/shapes/CMakeLists.txt
  tests/shapes/testSurfaceMesh.cpp
Labels: IO-Visualisation, Shapes, ready for review :+1:

#1511 Qt5 default version for Qt
  ChangeLog.md
  cmake/CheckDGtalOptionalDependencies.cmake
Labels: ready for review :+1:
