Repository DGtal-team/DGtal, pull requests merged in 2021-02, with the labels that each got.

#1548 Bugfix in Digital Surface Regularization
  ChangeLog.md
  src/DGtal/geometry/surfaces/DigitalSurfaceRegularization.ih
Labels: ready for review :+1:

#1550 Update CGAL components in cmake
  ChangeLog.md
  cmake/CheckDGtalOptionalDependencies.cmake
  cmake/DGtalConfig.cmake.in
Labels: Compilation Issue

#1547 Normal vector estimation based on plane-probing approaches
  ChangeLog.md
  examples/geometry/surfaces/CMakeLists.txt
  examples/geometry/surfaces/exampleMaximalSegmentSliceEstimation.cpp
  examples/geometry/surfaces/examplePlaneProbingParallelepipedEstimator.cpp
  examples/geometry/surfaces/examplePlaneProbingSurfaceLocalEstimator.cpp
  examples/geometry/surfaces/examplePlaneProbingTetrahedronEstimator.cpp
  src/DGtal/doc/global.bib
  src/DGtal/geometry/curves/GreedySegmentation.h
  src/DGtal/geometry/curves/SaturatedSegmentation.h
  src/DGtal/geometry/doc/images/maximalseg-ellipsoid-slices.png
  src/DGtal/geometry/doc/images/plane-probing-illustration-cube.png
  src/DGtal/geometry/doc/images/plane-probing-start-frame.png
  src/DGtal/geometry/doc/images/plane-probing-update-H.png
  src/DGtal/geometry/doc/moduleMaximalSegmentSliceEstimation.dox
  src/DGtal/geometry/doc/modulePlaneProbing.dox
  src/DGtal/geometry/doc/packageGeometry.dox
  src/DGtal/geometry/helpers/PlaneProbingEstimatorHelper.h
  src/DGtal/geometry/helpers/PlaneProbingEstimatorHelper.ih
  src/DGtal/geometry/surfaces/ArithmeticalDSSComputerOnSurfels.h
  src/DGtal/geometry/surfaces/ArithmeticalDSSComputerOnSurfels.ih
  src/DGtal/geometry/surfaces/DigitalPlanePredicate.h
  src/DGtal/geometry/surfaces/DigitalPlanePredicate.ih
  src/DGtal/geometry/surfaces/DigitalSurfacePredicate.h
  src/DGtal/geometry/surfaces/DigitalSurfacePredicate.ih
  src/DGtal/geometry/surfaces/ParallelStrip.h
  src/DGtal/geometry/surfaces/estimation/MaximalSegmentSliceEstimation.h
  src/DGtal/geometry/surfaces/estimation/MaximalSegmentSliceEstimation.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingDigitalSurfaceLocalEstimator.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingDigitalSurfaceLocalEstimator.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingHNeighborhood.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingHNeighborhood.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingNeighborhood.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingNeighborhood.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingParallelepipedEstimator.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingParallelepipedEstimator.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingR1Neighborhood.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingR1Neighborhood.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingRNeighborhood.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingRNeighborhood.ih
  src/DGtal/geometry/surfaces/estimation/PlaneProbingTetrahedronEstimator.h
  src/DGtal/geometry/surfaces/estimation/PlaneProbingTetrahedronEstimator.ih
  src/DGtal/topology/DigitalSurface2DSlice.h
  tests/geometry/surfaces/CMakeLists.txt
  tests/geometry/surfaces/testArithmeticalDSSComputerOnSurfels.cpp
  tests/geometry/surfaces/testDigitalPlanePredicate.cpp
  tests/geometry/surfaces/testPlaneProbingParallelepipedEstimator.cpp
  tests/geometry/surfaces/testPlaneProbingTetrahedronEstimator.cpp
Labels: Geometry

#1551 Speeding up compilation of the tests that rely on Catch2
  ChangeLog.md
  tests/CMakeLists.txt
  tests/DGtalCatch.cpp
  tests/DGtalCatch.h
  tests/TestFunctions.cmake
Labels: Build, ready for review :+1:
