Repository DGtal-team/DGtal, pull requests merged in 2022-03, with the labels that each got.

#1634 Various small edits in ImageFromSetAdd and IO ITK
  ChangeLog.md
  src/DGtal/images/ImageSelector.h
  src/DGtal/images/ImageSelector.ih
  src/DGtal/images/imagesSetsUtils/ImageFromSet.h
  src/DGtal/images/imagesSetsUtils/ImageFromSet.ih
  src/DGtal/io/ITKIOTrait.h
  src/DGtal/io/readers/GenericReader.h
  src/DGtal/io/readers/GenericReader.ih
  src/DGtal/io/writers/GenericWriter.ih
  tests/io/readers/testITKReader.cpp
  tests/io/writers/testGenericWriter.cpp
  tests/samples/lobsterCroped2.nii
  tests/samples/lobsterCroped2.nii.gz
Labels: IO-Visualisation, Image, ready for review :+1:

#1638 Fix testLongvol and testCompressedVolWriter
  .github/workflows/buildAndDocumentation-PR.yml
  ChangeLog.md
  src/DGtal/io/readers/LongvolReader.h
  tests/io/testLongvol.cpp
  tests/io/writers/testCompressedVolWriter.cpp
Labels: IO-Visualisation

#1641 OpenMP Fix on M1
  .github/workflows/buildAndDocumentation-PR.yml
  ChangeLog.md
  cmake/CheckDGtalOptionalDependencies.cmake
  cmake/DGtalConfig.cmake.in
Labels: ready for review :+1:
