Repository DGtal-team/DGtal, pull requests merged in 2022-10, with the labels that each got.

#1650 Preparing release1.3
  .github/workflows/buildAndDocumentation-PR.yml
  .github/workflows/buildAndDocumentation.yml
  CMakeLists.txt
  ChangeLog.md
  cmake/DGtalConfig.cmake.in
  examples/geometry/curves/exampleDigitalConvexity.cpp
  examples/polyscope-examples/exampleBunnyHead.cpp
  examples/shapes/mesh3DConstructionAndVisualisation.cpp
  examples/shapes/sphereCotangentLaplaceOperator.cpp
  src/DGtal/geometry/volumes/TangencyComputer.h
  src/DGtal/geometry/volumes/distance/ChamferNorm2D.ih
  src/DGtal/geometry/volumes/distance/PowerMap.ih
  src/DGtal/helpers/Shortcuts.h
  src/DGtal/io/readers/MeshReader.h
  src/DGtal/io/readers/MeshReader.ih
  src/DGtal/io/readers/SurfaceMeshReader.ih
  src/DGtal/io/writers/MeshWriter.ih
  src/DGtal/io/writers/STBWriter.ih
  src/DGtal/shapes/Mesh.h
  src/DGtal/shapes/Mesh.ih
  src/DGtal/shapes/MeshHelpers.h
  src/DGtal/shapes/MeshHelpers.ih
  src/DGtal/shapes/MeshVoxelizer.h
  src/DGtal/shapes/MeshVoxelizer.ih
  src/DGtal/topology/VoxelComplex.h
  tests/geometry/surfaces/testArithmeticalDSSComputerOnSurfels.cpp
  tests/shapes/testMesh.cpp
  tests/shapes/testMeshDisplay.cpp
Labels: ready for review :+1:

#1659 Fixing issues on non-manifold edges in the vector field processing
  ChangeLog.md
  examples/polyscope-examples/dgtalCalculus-geodesic.cpp
  examples/polyscope-examples/exampleVectorHeatMethod.cpp
  src/DGtal/dec/GeodesicsInHeat.h
  src/DGtal/dec/PolygonalCalculus.h
  src/DGtal/dec/VectorsInHeat.h
  tests/dec/testGeodesicsInHeat.cpp
  tests/dec/testPolygonalCalculus.cpp
  tests/dec/testVectorsInHeat.cpp
Labels: ready for review :+1:, DEC

#1660 minor edits in power map documentation
  ChangeLog.md
  examples/geometry/volumes/distance/toricdomainvolumetric.cpp
  src/DGtal/geometry/doc/moduleVolumetric.dox
  src/DGtal/geometry/volumes/distance/DistanceTransformation.h
  src/DGtal/geometry/volumes/distance/PowerMap.h
  tests/geometry/volumes/distance/testDistanceTransformation.cpp
  tests/geometry/volumes/distance/testDistanceTransformationND.cpp
Labels: ready for review :+1:

#1662 Try to fix warning in DistanceBreadthFirstVisitor
  ChangeLog.md
  src/DGtal/graph/DistanceBreadthFirstVisitor.h
Labels: ready for review :+1:, BugFix
