Repository DGtal-team/DGtal, pull requests merged in 2022-02, with the labels that each got.

#1626 Point2DEmbedderIn3D adds
  .github/workflows/buildAndDocumentation-PR.yml
  ChangeLog.md
  src/DGtal/kernel/BasicPointFunctors.h
  tests/kernel/testBasicPointFunctors.cpp
Labels: ready for review :+1:

#1630 Disabling examples build by default.
  ChangeLog.md
  cmake/BuildExamples.cmake
  tests/io/writers/testCompressedVolWriter.cpp
Labels: Base, ready for review :+1:, Project

#1635 Update buildAndDocumentation-PR.yml
  .github/workflows/buildAndDocumentation-PR.yml
  ChangeLog.md
Labels: ready for review :+1:

#1631 interior / exterior voxel coordinates associatd to a surfel (signed (n-1)-cell).
  ChangeLog.md
  src/DGtal/topology/CPreCellularGridSpaceND.h
  src/DGtal/topology/KhalimskyPreSpaceND.h
  src/DGtal/topology/KhalimskyPreSpaceND.ih
  src/DGtal/topology/KhalimskySpaceND.h
  src/DGtal/topology/KhalimskySpaceND.ih
  src/DGtal/topology/doc/moduleDigitalSurfaces.dox
  tests/topology/testKhalimskySpaceND.cpp
Labels: Topology, ready for review :+1:
