Repository DGtal-team/DGtal, pull requests merged in 2022-07, with the labels that each got.

#1648 Removing imagemagick and using stb_image instead
  .github/workflows/buildAndDocumentation-PR.yml
  .github/workflows/checkDoxygenDocumentation.sh
  ChangeLog.md
  README.md
  cmake/CheckDGtalOptionalDependencies.cmake
  cmake/DGtalConfig.cmake.in
  cmake/DGtalConfigGenerator.cmake
  cmake/FindMagick.cmake
  doc/doxy.config.in
  examples/arithmetic/lower-integer-convex-hull.cpp
  examples/geometry/curves/CMakeLists.txt
  examples/geometry/curves/freemanChainDisplay.cpp
  examples/samples/contourS.gif
  examples/tutorial-examples/FMMErosion.cpp
  src/DGtal/doc/mainpage.dox
  src/DGtal/doc/moduleBuildDGtal.dox
  src/DGtal/doc/moduleHowToUseDGtal-qmake.dox
  src/DGtal/doc/tutorials/tutoImageManipulations.dox
  src/DGtal/images/ImageContainerBySTLMap.ih
  src/DGtal/io/doc/moduleIO.dox
  src/DGtal/io/readers/GenericReader.h
  src/DGtal/io/readers/GenericReader.ih
  src/DGtal/io/readers/MagickReader.h
  src/DGtal/io/readers/MagickReader.ih
  src/DGtal/io/readers/STBReader.h
  src/DGtal/io/readers/STBReader.ih
  src/DGtal/io/writers/GenericWriter.ih
  src/DGtal/io/writers/MagickWriter.h
  src/DGtal/io/writers/PPMWriter.h
  src/DGtal/io/writers/RawWriter.h
  src/DGtal/io/writers/STBWriter.h
  src/DGtal/io/writers/STBWriter.ih
  src/stb/stb_image.h
  src/stb/stb_image_write.h
  tests/io/readers/CMakeLists.txt
  tests/io/readers/testMagickReader.cpp
  tests/io/readers/testSTBReader.cpp
  tests/io/writers/CMakeLists.txt
  tests/io/writers/testGenericWriter.cpp
  tests/io/writers/testMagickWriter.cpp
  tests/io/writers/testSTBWriter.cpp
  tests/samples/color64.bmp
  tests/samples/color64.gif
  tests/samples/color64.jpg
  tests/samples/color64.tga
  tests/samples/contourS.gif
Labels: IO-Visualisation, ready for review :+1:

#1647 Fix issue on angle tolerance in computeHullThickness
  ChangeLog.md
  src/DGtal/geometry/tools/Hull2DHelpers.h
  src/DGtal/geometry/tools/Hull2DHelpers.ih
  tests/geometry/tools/testConvexHull2D.cpp
Labels: ready for review :+1:, BugFix

#1653 Mesh reader fix comment
  ChangeLog.md
  src/DGtal/io/readers/MeshReader.ih
Labels: ready for review :+1:

#1646 Adding vector calculus operators to PolygonalCalculus class, with few examples
  AUTHORS
  ChangeLog.md
  examples/dec/CMakeLists.txt
  examples/polyscope-examples/CMakeLists.txt
  examples/polyscope-examples/exampleBunnyHead.cpp
  examples/polyscope-examples/exampleHarmonicParametrization.cpp
  examples/polyscope-examples/exampleVectorHeatMethod.cpp
  examples/samples/bimbaPoly.mtl
  examples/samples/bimbaPoly.obj
  examples/samples/bunnyhead.obj
  examples/samples/bunnyheadhole.obj
  src/DGtal/dec/GeodesicsInHeat.h
  src/DGtal/dec/PolygonalCalculus.h
  src/DGtal/dec/VectorsInHeat.h
  src/DGtal/dec/doc/images/poly/VHM_1_source.png
  src/DGtal/dec/doc/images/poly/VHM_1_source_solve.png
  src/DGtal/dec/doc/images/poly/VHM_multiple_sources.png
  src/DGtal/dec/doc/images/poly/VHM_multiple_sources_solve.png
  src/DGtal/dec/doc/images/poly/bimba-1source.png
  src/DGtal/dec/doc/images/poly/bimba-1vf.png
  src/DGtal/dec/doc/images/poly/bimba-geodesic.png
  src/DGtal/dec/doc/images/poly/bimba-nsources.png
  src/DGtal/dec/doc/images/poly/bimba-nvf.png
  src/DGtal/dec/doc/images/poly/bimba-orig.png
  src/DGtal/dec/doc/images/poly/transport_to_face.png
  src/DGtal/dec/doc/modulePolygonalCalculus.dox
  src/DGtal/dec/doc/moduleVectorsInHeat.dox
  src/DGtal/dec/doc/packageDEC.dox
  src/DGtal/doc/global.bib
  src/DGtal/io/doc/moduleIO.dox
  src/DGtal/math/linalg/EigenSupport.h
  src/DGtal/shapes/SurfaceMesh.h
  src/DGtal/topology/HalfEdgeDataStructure.h
  tests/dec/CMakeLists.txt
  tests/dec/testPolygonalCalculus.cpp
  tests/dec/testVectorsInHeat.cpp
  tests/shapes/testSurfaceMesh.cpp
Labels: ready for review :+1:, DEC
