Repository DGtal-team/DGtal, pull requests merged in 2023-02, with the labels that each got.

#1683 GitHub Actions commands on PR comments
  .github/workflows/buildAndDocumentation-PR.yml
  .github/workflows/commands.yml
  ChangeLog.md
  src/DGtal/geometry/volumes/BoundedLatticePolytopeCounter.h
Labels: ready for review :+1:

#1684 New method to change the mode of the light position in Viewer3D
  ChangeLog.md
  src/DGtal/io/viewers/Viewer3D.h
  src/DGtal/io/viewers/Viewer3D.ih
Labels: ready for review :+1:

#1686 option to put material part inside obj file
  ChangeLog.md
  src/DGtal/io/readers/MeshReader.ih
  src/DGtal/io/writers/MeshWriter.h
  src/DGtal/io/writers/MeshWriter.ih
Labels: IO-Visualisation, ready for review :+1:

#1680 Removing ImageSelector for faster build (ITK)
  ChangeLog.md
  examples/geometry/surfaces/exampleIntegralInvariantCurvature2D.cpp
  examples/topology/ctopo-fillContours.cpp
  src/Board/Board.cpp
  src/DGtal/arithmetic/CPositiveIrreducibleFraction.h
  src/DGtal/base/CBackInsertable.h
  src/DGtal/base/CBidirectionalRange.h
  src/DGtal/base/CBidirectionalRangeFromPoint.h
  src/DGtal/base/CBidirectionalRangeWithWritableIterator.h
  src/DGtal/base/CBidirectionalRangeWithWritableIteratorFromPoint.h
  src/DGtal/base/CConstBidirectionalRangeFromPoint.h
  src/DGtal/base/CConstSinglePassRangeFromPoint.h
  src/DGtal/base/Common.h
  src/DGtal/geometry/surfaces/estimation/LocalConvolutionNormalVectorEstimator.h
  src/DGtal/geometry/volumes/BoundedLatticePolytopeCounter.h
  src/DGtal/geometry/volumes/distance/DistanceTransformation.h
  src/DGtal/shapes/Mesh.ih
  src/DGtal/topology/helpers/Surfaces.ih
  tests/arithmetic/testArithmeticDSS-benchmark.cpp
  tests/arithmetic/testStandardDSLQ0-LSB-reversedSmartDSS-benchmark.cpp
  tests/arithmetic/testStandardDSLQ0-LrSB-reversedSmartDSS-benchmark.cpp
  tests/arithmetic/testStandardDSLQ0-reversedSmartDSS-benchmark.cpp
  tests/arithmetic/testStandardDSLQ0-smartDSS-benchmark.cpp
  tests/graph/testBreadthFirstPropagation.cpp
  tests/graph/testDepthFirstPropagation.cpp
  tests/graph/testDistancePropagation.cpp
  tests/topology/testDigitalSurface.cpp
  tests/topology/testObject-benchmark.cpp
  tests/topology/testSurfaceHelper.cpp
Labels: Build, ready for review :+1:

#1685 Upgrading pybind11
  ChangeLog.md
  cmake/PythonWrappings.cmake
Labels: ready for review :+1:
