Repository DGtal-team/DGtal, pull requests merged in 2023-11, with the labels that each got.

#1708 Fix PointListReader for reading single-element (Point1D case) per line
  ChangeLog.md
  src/DGtal/io/readers/PointListReader.ih
  tests/io/readers/testPointListReader.cpp
  tests/samples/polygons.dat
Labels: waiting author feedbacks, BugFix

#1709 Mesh remove isolated vertex
  ChangeLog.md
  src/DGtal/io/readers/MeshReader.h
  src/DGtal/io/readers/MeshReader.ih
  src/DGtal/shapes/Mesh.h
  src/DGtal/shapes/Mesh.ih
  src/DGtal/shapes/MeshHelpers.h
  src/DGtal/shapes/MeshHelpers.ih
  tests/shapes/testMesh.cpp
Labels: ready for review :+1:, Shapes

#1711 Cleaning up unnecessary ModuleSRC files
  CMakeLists.txt
  ChangeLog.md
  src/DGtal/helpers/ModuleSRC.cmake
  src/DGtal/kernel/ModuleSRC.cmake
Labels: ready for review :+1:
