Repository DGtal-team/DGtal, pull requests merged in 2024-06, with the labels that each got.

#1727 Exposing winding number values
  ChangeLog.md
  src/DGtal/shapes/WindingNumbersShape.h
Labels: ready for review :+1:

#1728 Deps in DGTAL_LIBRARIES
  ChangeLog.md
  cmake/DGtalConfig.cmake.in
Labels: ready for review :+1:

#1717 Add triangle to convexity helper
  ChangeLog.md
  src/DGtal/geometry/doc/moduleDigitalConvexity.dox
  src/DGtal/geometry/volumes/BoundedLatticePolytopeCounter.ih
  src/DGtal/geometry/volumes/ConvexityHelper.h
  src/DGtal/geometry/volumes/ConvexityHelper.ih
  src/DGtal/geometry/volumes/DigitalConvexity.h
  src/DGtal/geometry/volumes/DigitalConvexity.ih
  tests/geometry/volumes/testConvexityHelper.cpp
  tests/geometry/volumes/testDigitalConvexity.cpp
Labels: Geometry, ready for review :+1:

#1730 Helper functor in PolygonalCalculus to project vertices onto their tangent plane.
  .github/workflows/build-master.yml
  .github/workflows/buildAndDocumentation-PR.yml
  .github/workflows/pythonBindings-PR.yml
  .github/workflows/pythonBindings-Pypi.yml
  ChangeLog.md
  README.md
  cmake/CheckDGtalDependencies.cmake
  conanfile.txt
  examples/polyscope-examples/dgtalCalculus-geodesic.cpp
  src/DGtal/dec/PolygonalCalculus.h
  src/DGtal/dec/doc/images/poly/corrected-with.png
  src/DGtal/dec/doc/images/poly/corrected-without.png
  src/DGtal/dec/doc/modulePolygonalCalculus.dox
  src/DGtal/doc/global.bib
  src/DGtal/doc/mainpage.dox
  src/DGtal/doc/moduleBuildDGtal.dox
Labels: ready for review :+1:

#1726 Fix seg fault and enable parameter error=0 in FrechetShortcut
  ChangeLog.md
  src/DGtal/geometry/curves/FrechetShortcut.h
  src/DGtal/geometry/curves/FrechetShortcut.ih
  tests/geometry/curves/testFrechetShortcut.cpp
  tests/samples/Plant054.dat
  tests/samples/beetle-1.dat
Labels: waiting author feedbacks
