Repository DGtal-team/DGtal, pull requests merged in 2025-07, with the labels that each got.

#1782 Python shortcuts
  ChangeLog.md
  src/DGtal/doc/mainpage.dox
  src/DGtal/doc/packagePython.dox
  src/DGtal/helpers/Shortcuts.h
  wrap/CMakeLists.txt
  wrap/deploy/__init__.py
  wrap/dgtal_init_py.cpp
  wrap/helpers/CMakeLists.txt
  wrap/helpers/Shortcuts_py.cpp
  wrap/helpers/helpers_init.cpp
  wrap/tutorials/IntegralInvariantEstimates.py
Labels: 2.0

#1784 Voronoi map shortcuts
  ChangeLog.md
  examples/tutorial-examples/shortcuts-geometry.cpp
  src/DGtal/doc/tutorials/images/voronoimapl1.png
  src/DGtal/doc/tutorials/images/voronoimapl2.png
  src/DGtal/doc/tutorials/moduleShortcuts.dox
  src/DGtal/helpers/ShortcutsGeometry.h
  wrap/helpers/Shortcuts_py.cpp
Labels: Geometry, 2.0

#1788 Add material surface mesh reader
  ChangeLog.md
  src/DGtal/io/readers/SurfaceMeshReader.h
  src/DGtal/io/readers/SurfaceMeshReader.ih
Labels: IO-Visualisation, ready for review :+1:

#1789 Add full convexity for open triangles in 3D and full covering test for segments and triangles in 3D.
  ChangeLog.md
  src/DGtal/geometry/doc/moduleDigitalConvexity.dox
  src/DGtal/geometry/doc/moduleEnvelope.dox
  src/DGtal/geometry/surfaces/ParallelStrip.h
  src/DGtal/geometry/volumes/BoundedLatticePolytope.h
  src/DGtal/geometry/volumes/BoundedLatticePolytope.ih
  src/DGtal/geometry/volumes/BoundedLatticePolytopeCounter.h
  src/DGtal/geometry/volumes/BoundedLatticePolytopeCounter.ih
  src/DGtal/geometry/volumes/ConvexityHelper.h
  src/DGtal/geometry/volumes/ConvexityHelper.ih
  src/DGtal/geometry/volumes/DigitalConvexity.h
  src/DGtal/geometry/volumes/DigitalConvexity.ih
  tests/geometry/volumes/testConvexityHelper.cpp
  tests/geometry/volumes/testDigitalConvexity.cpp
Labels: Geometry, ready for review :+1:

#1792 Doc Display3D edits and small adjust
  .github/workflows/build-PR-master.yml
  ChangeLog.md
  doc/doxygen-awesome-css-main/doxygen-awesome.css
  examples/io/viewers/CMakeLists.txt
  examples/io/viewers/viewer3D-5-colors.cpp
  examples/io/viewers/viewer3D-8-2DSliceImages.cpp
  examples/io/viewers/viewer3D-8bis-2Dimages.cpp
  src/DGtal/images/ConstImageAdapter.h
  src/DGtal/io/Display3D.h
  src/DGtal/io/Display3D.ih
  src/DGtal/io/doc/images/viewer3D-4-modes.png
  src/DGtal/io/doc/images/viewer3D-8bis.png
  src/DGtal/io/doc/moduleDisplay3D.dox
  src/DGtal/kernel/BasicPointFunctors.h
Labels: ready for review :+1:
